[project]
name = "potato-leaf-disease"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.11.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "uv>=0.6.14",
]
